apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j0lca1nup-python
  janus-idp.io/tekton: j0lca1nup-python
  backstage.io/kubernetes-id: j0lca1nup-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j0lca1nup-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
